services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: python:3.9.16-slim
    init: true
    command: bash -c "apt-get update && apt-get install git"
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock


